export interface Game {
  ageRating: number,
  createdAt: Date,
  description: string,
  developer: string,
  gameId: string,
  gender: string,
  itIsInPromotion: boolean,
  name: string,
  plataform: string,
  price: number,
  publisher: string,
  releaseDate: Date,
  reviews: any,
  userId: string,
}
